version: '2'
services:
    mongodb:
        image: mongo:latest
        ports: 
            - "27017:27017"
        volumes:
            - ./db/mongo:/data/db

    mysqldb:
        image: mysql:latest
        environment:
         - MYSQL_ROOT_PASSWORD=servidor
         - MYSQL_DATABASE=your-pass
        ports:
          - "3307:3306"