
# Extract Tests
require_relative 'extract/test_parliamentarians_db_extract'
require_relative 'extract/test_parliamentarians_requester'
require_relative 'extract/test_parliamentarians_extractor'

# Transform Tests
require_relative 'transform/test_parliamentarians_db_transform'
require_relative 'transform/test_parliamentarians_parser'
require_relative 'transform/test_parliamentarians_transformer'
